import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import MainLayout from "./../MainLayout";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "800"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Fashion",
  description: "Generated by Fashion",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
